(* Generated by Makefile - edition is futile *)
let version = "0.0.0"
let ocaml_version = "4.07.1"
let ocamlfind = "ocamlfind"
let ocamlpath = ""
let build_date = "Wed, 10 Feb 2021 21:45:16 +0100"
let build_host = "zen"
