(* Generated by Makefile - edition is futile *)
let version = "0.2.0"
let ocaml_version = "4.07.1"
let ocamlfind = "ocamlfind"
let ocamlpath = ""
let build_date = "Sat, 27 Feb 2021 09:22:03 +0100"
let build_host = "poum.happyleptic.org"
