(* Generated by Makefile - edition is futile *)
let version = "0.1.0"
let ocaml_version = "4.07.1"
let ocamlfind = "ocamlfind"
let ocamlpath = ""
let build_date = "Fri, 12 Feb 2021 08:41:12 +0100"
let build_host = "poum.happyleptic.org"
